import '../styles/main.scss';
import "../styles/global.css"
import { Roboto } from 'next/font/google'
import Providers from '@/components/other/Providers';

const font = Roboto({
	weight: ['400', '700'],
	subsets: ['latin'],
  })

export const metadata = {
	title: 'CV Generator',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
	  <html lang="en">
		<body className={font.className}>
				<Providers>
					{children}
				</Providers>
		</body>
	  </html>
	);
  }
